### ISSUE TITLE
Fails to sync on mainnet

### ISSUE THREAD

**Issue by OverlordQ** [smartbch/smartbch#22]
```
ScanEntriesLite 0.95 103582208/109033848
This Node ID: 7009f8f9fb0e940122011a9d301bd395f7bde43c
I[2021-09-07|06:28:40.921] Starting multiAppConn service                module=proxy impl=multiAppConn
I[2021-09-07|06:28:40.921] Starting localClient service                 module=abci-client connection=query impl=localClient
I[2021-09-07|06:28:40.921] Starting localClient service                 module=abci-client connection=snapshot impl=localClient
I[2021-09-07|06:28:40.921] Starting localClient service                 module=abci-client connection=mempool impl=localClient
I[2021-09-07|06:28:40.921] Starting localClient service                 module=abci-client connection=consensus impl=localClient
I[2021-09-07|06:28:40.921] Starting EventBus service                    module=events impl=EventBus
I[2021-09-07|06:28:40.921] Starting PubSub service                      module=pubsub impl=PubSub
I[2021-09-07|06:28:40.921] Starting IndexerService service              module=txindex impl=IndexerService
I[2021-09-07|06:28:40.921] ABCI Handshake App Info                      module=consensus height=238786 hash=E2752A60A062BABD81D3E21602145CC9EF6C9C33092D6A4D95E621B6C859FC2E software-version= protocol-version=0
I[2021-09-07|06:28:40.921] ABCI Replay Blocks                           module=consensus appHeight=238786 storeHeight=238787 stateHeight=238786
I[2021-09-07|06:28:40.921] Replay last block using real app             module=consensus
ERROR: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected E2752A60A062BABD81D3E21602145CC9EF6C9C33092D6A4D95E621B6C859FC2E, got BB298C057E9B1D2D27B1EDDC473D8B341CE35454889342C6BAA0A8EC682A0F6A
```

**Comment by giviz** [comment]
I have the exact same error, fresh install, debian OS, failing on the same block.

**Comment by giviz** [comment]
The issue seems to be solved in 0.3.3, full sync complete without error :)

**Comment by zquestz** [comment]
Just saw this on 0.3.3...

```
textPayload: "ERROR: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 31691B385E989E5C71266114E72C2B33710974F13DA7A34AE1475BB8B5BB9A31, got 628D760F403E9551B9C9002C8B3FC9023D4A83ABCE71C7BC4FC095EB3B9670C5
```

**Comment by JHong111** [comment]
I can't synchronize with 0.3.3 or the latest code

I[2021-09-09|12:58:06.396] Added peer                                   module=p2p peer="Peer{MConn{18.138.237.114:26656} 9942597c62826d0c25b65203cde1574470653e6e out}"
I[2021-09-09|12:58:06.796] executed block                               module=state height=1 num_valid_txs=0 num_invalid_txs=0
I[2021-09-09|12:58:06.829] committed state                              module=state height=1 num_txs=0 app_hash=2A9219CB627D6D183F8066113DB39ACD81B25A39C3EB023CA4EE1B171511E35F
I[2021-09-09|12:58:06.830] indexed block                                module=txindex height=1
panic: Failed to process committed block (2:B165783F1AD6352F66144533478C17206F7C0F516D1CBB67713848C04448D6CF): wrong Block.Header.AppHash.  Expected 2A9219CB627D6D183F8066113DB39ACD81B25A39C3EB023CA4EE1B171511E35F, got B899D1FB272F0ECBEA60B645D7E4C363ECE9889CF25743BAE14B4D3EB08BABBC

goroutine 3947140 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc01506f340, 0x0)
        /root/godata/pkg/mod/github.com/tendermint/tendermint@v0.34.10/blockchain/v0/reactor.go:401 +0x15bf
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /root/godata/pkg/mod/github.com/tendermint/tendermint@v0.34.10/blockchain/v0/reactor.go:110 +0x8c

**Comment by zxh0** [comment]
hi @OverlordQ @giviz @zquestz 
If it is possible, could you zip your  ~/.smartbchd dir and give us a copy? It will help us to find the bug.

**Comment by wangkui0508** [comment]
If you fail at 238786, that is because you do not configure the BCHN PRC Server. Every smartbchd node needs to connect to a BCHN RPC Server to work. Note these works: "Third, open the ~/.smartbchd/config/app.toml file to modify the information of the bitcoincashnode's client with RPC enabled."  (https://github.com/smartbch/docs/blob/main/mainnet.md )

**Comment by smacz42** [comment]
> If you fail at 238786, that is because you do not configure the BCHN PRC Server. Every smartbchd node needs to connect to a BCHN RPC Server to work. Note these works: "Third, open the ~/.smartbchd/config/app.toml file to modify the information of the bitcoincashnode's client with RPC enabled." (https://github.com/smartbch/docs/blob/main/mainnet.md )

The docs don't mention which section of the toml file that should go under. Those parameters are not there that I can tell. Also, there is no app.toml in this repo. Is it in another repo?

**Comment by nlandeker** [comment]
Hello,

i have similar issue:
`ERROR: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected E2752A60A062BABD81D3E21602145CC9EF6C9C33092D6A4D95E621B6C859FC2E, got BB298C057E9B1D2D27B1EDDC473D8B341CE35454889342C6BAA0A8EC682A0F6A`

But I have set RPC info connecting to synced BCH mainnet node. Do you have any idea what the issue could be?

**Comment by RootBlocker** [comment]
I am getting the same issue, it keeps getting stuck syncing at the exact same block.

**Comment by modenero** [comment]
My mainnet and testnet nodes have been down for a month now. 
Still trying to sort all this out, but it's tough to find the time.

**On mainnet:**

```
0|smartbch | ERROR: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected A5A2608CA44CE89247A39788AABAF0A54CBEF8CFBB7796062A1B29A53168FAEF, got D7F1C51827CA1FBD71B48F960321A21DCA9DA05D7F8791F89C3B8FB73482B4AD
```

what's causing all of these `Block.Header` issues??

**and on testnet I'm having peer connectivity issues:**

```
0|smartbch | I[2022-02-16|04:12:28.452] No addresses to dial. Falling back to seeds  module=pex 
0|smartbch | I[2022-02-16|04:12:28.453] Dialing peer                                 module=p2p address=30da56fe4b542d54c8de7c8ac653863bf859ffbb@52.77.241.179:26656
0|smartbch | E[2022-02-16|04:12:28.694] Error dialing seed                           module=p2p err="dial tcp 52.77.241.179:26656: connect: connection refused" seed=30da56fe4b542d54c8de7c8ac653863bf859ffbb@52.77.241.179:26656
0|smartbch | E[2022-02-16|04:12:28.695] Couldn't connect to any seeds                module=p2p 
0|smartbch | I[2022-02-16|04:12:58.464] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
0|smartbch | I[2022-02-16|04:12:58.464] No addresses to dial. Falling back to seeds  module=pex 
0|smartbch | I[2022-02-16|04:12:58.465] Dialing peer                                 module=p2p address=30da56fe4b542d54c8de7c8ac653863bf859ffbb@52.77.241.179:26656
0|smartbch | E[2022-02-16|04:12:58.706] Error dialing seed                           module=p2p err="dial tcp 52.77.241.179:26656: connect: connection refused" seed=30da56fe4b542d54c8de7c8ac653863bf859ffbb@52.77.241.179:26656
0|smartbch | E[2022-02-16|04:12:58.706] Couldn't connect to any seeds                module=p2p 
0|smartbch | I[2022-02-16|04:13:28.175] Saving AddrBook to file                      module=p2p book=/root/.smartbchd/config/addrbook.json size=0
0|smartbch | I[2022-02-16|04:13:28.458] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
0|smartbch | I[2022-02-16|04:13:28.458] No addresses to dial. Falling back to seeds  module=pex 
0|smartbch | I[2022-02-16|04:13:28.458] Dialing peer                                 module=p2p address=30da56fe4b542d54c8de7c8ac653863bf859ffbb@52.77.241.179:26656
0|smartbch | E[2022-02-16|04:13:28.680] Error dialing seed                           module=p2p err="dial tcp 52.77.241.179:26656: connect: connection refused" seed=30da56fe4b542d54c8de7c8ac653863bf859ffbb@52.77.241.179:26656
0|smartbch | E[2022-02-16|04:13:28.681] Couldn't connect to any seeds                module=p2p 
```

**once resolved, my nodes will run from:**
https://smartbch.devops.cash/mainnet
https://smartbch.devops.cash/testnet

Please let me know what adt'l info I can provide to help in resolving these issues.

Cheers!
Shomari

**Comment by helldealer** [comment]
Hello, @nlandeker @modenero @RootBlocker,  we have encountered a lot of these similar problems, which can be solved by clear the node working directory, using the latest binaries from the reference documentation, and re-syncing the blocks. The documentation is as follows: 
https://docs.smartbch.org/smartbch/mainnet
https://docs.smartbch.org/smartbch/testnets 
We frequently add new features and fix bugs, and these changes are always synced to the above documentation in time. If you still get errors about appHash after doing the above, you can join the [[SmartBCH developers channel ](https://t.me/smartbchdevelopers)](https://t.me/smartbchdevelopers)on Telegram

**Comment by modenero** [comment]
@helldealer thanks for the recommendation.

> clear the node working directory

should this command sequence do the job? It's my understanding that `.smartbchd` is the working directory.

```
cp ~/smart_bch/smartbch/smartbchd ~/build/smartbchd
cd ~
rm -rf .smartbchd
~/build/smartbchd init mynode --chain-id 0x2711
wget https://github.com/smartbch/artifacts/releases/download/v0.0.4/dot.smartbchd.tgz
tar zxvf dot.smartbchd.tgz
cp -rf dot.smartbchd/* .smartbchd/
```

i think the problem is that I had several `dot.smartbchd.tgz` files from running that sequence several times:
- dot.smartbchd.tgz.1
- dot.smartbchd.tgz.2
- dot.smartbchd.tgz.3
- dot.smartbchd.tgz.4

so it's very likely that `tar zxvf dot.smartbchd.tgz` was unpacking "OLD" data.

starting testnet re-sync now. will update later..

**Comment by bitqwer** [comment]
bitcoincash abc client must run with txindex=1
