### ISSUE TITLE
block.AppHash does not match AppHash after replay

### ISSUE THREAD

**Issue by damascene** [smartbch/smartbch#26]
Hello, I'm having this issue after trying to start my smartbch node after upgrading to master:
```
ScanEntriesLite 0.65 1087526264/1673116800
ScanEntriesLite 0.70 1171183032/1673116800
ScanEntriesLite 0.75 1254839000/1673116800
ScanEntriesLite 0.80 1338494120/1673116800
ScanEntriesLite 0.85 1422149688/1673116800
ScanEntriesLite 0.90 1505806024/1673116800
ScanEntriesLite 0.95 1589462360/1673116800
pre fetch bch blocks: #708584 ~ #708593, latest: #708701
pre fetch bch blocks: #708595 ~ #708604, latest: #708701
pre fetch bch blocks: #708606 ~ #708615, latest: #708701
pre fetch bch blocks: #708617 ~ #708626, latest: #708701
pre fetch bch blocks: #708628 ~ #708637, latest: #708701
pre fetch bch blocks: #708639 ~ #708648, latest: #708701
pre fetch bch blocks: #708650 ~ #708659, latest: #708701
pre fetch bch blocks: #708661 ~ #708670, latest: #708701
pre fetch bch blocks: #708672 ~ #708681, latest: #708701
This Node ID: 525de84eb8ed4575b57d6a6eccd723dbd9ce4cf8
I[2021-10-08|14:03:03.197] Starting multiAppConn service                module=proxy impl=multiAppConn
I[2021-10-08|14:03:03.197] Starting localClient service                 module=abci-client connection=query impl=localClient
I[2021-10-08|14:03:03.198] Starting localClient service                 module=abci-client connection=snapshot impl=localClient
I[2021-10-08|14:03:03.198] Starting localClient service                 module=abci-client connection=mempool impl=localClient
I[2021-10-08|14:03:03.198] Starting localClient service                 module=abci-client connection=consensus impl=localClient
I[2021-10-08|14:03:03.199] Starting EventBus service                    module=events impl=EventBus
I[2021-10-08|14:03:03.199] Starting PubSub service                      module=pubsub impl=PubSub
I[2021-10-08|14:03:03.200] Starting IndexerService service              module=txindex impl=IndexerService
I[2021-10-08|14:03:03.201] ABCI Handshake App Info                      module=consensus height=1073103 hash=5C93D29D4749065FB92B8D47642DF0CC87FC9123FDEF2568DA6726E1FF942AE5 software-version= protocol-version=0
I[2021-10-08|14:03:03.202] ABCI Replay Blocks                           module=consensus appHeight=1073103 storeHeight=1073574 stateHeight=1073574
I[2021-10-08|14:03:03.202] Applying block                               module=consensus height=1073104
I[2021-10-08|14:03:03.217] executed block                               module=consensus height=1073104 num_valid_txs=0 num_invalid_txs=0
I[2021-10-08|14:03:03.274] Applying block                               module=consensus height=1073105
panic: block.AppHash does not match AppHash after replay. Got 26CFEC21DEDC5E99E91691F170714B41C797B86C462F1F37D21A3B24610CF678, expected 670B45DF7A05BAB79E3DC38436213BB11385471FAD22CF80E2995977631CDB6F.

Block: Block{
  Header{
    Version:        {11 0}
    ChainID:        0x2710
    Height:         1073105
    Time:           2021-10-08 13:04:44.186642446 +0000 UTC
    LastBlockID:    28647082CB54E6F93A6DC83FF4D414FEEF759CFB9E6760ACEC8DEC78BB2E2E53:1:857D56FF9983
    LastCommit:     B6DD5A8882DCB11E9000494903D28461E6E73E8931DFA0AB72009965D9D9D461
    Data:           831B084AA1E87DBF15879B6E854437F0A21B473B32BD0C19BC934FAE6DEE27FE
    Validators:     04A699211A4ED90334B20CD106CDD5A9C7E43DBF54833A78C3EEF9F980DF4496
    NextValidators: 04A699211A4ED90334B20CD106CDD5A9C7E43DBF54833A78C3EEF9F980DF4496
    App:            670B45DF7A05BAB79E3DC38436213BB11385471FAD22CF80E2995977631CDB6F
    Consensus:      DB82A3E5EC7A0994F3B78B258907CFF68320368782642AA9255985A28C938678
    Results:        E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Evidence:       E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Proposer:       8A3B04DB500735E05A1CD05ED9E00176954D8438
  }#EDE0A46D4DC456EEA82AE5869995D3A5A51472BC07F1ACC886B36C4C14507393
  Data{
    0BF13E9796D149BFA403A7B9228820DBA8C16EC937F362A5AA42097281EC63E3 (369 bytes)
    75A1F8A9B2A7AF5503A5339F686318A067A5B6295B87707CABF8F660F2A0FFEC (369 bytes)
    FAE839D33738E4C0CB34F58A4407EEF39E87F735C9BFF2FD648EBFE8244AC781 (369 bytes)
    A03C4891D3B54FADF1EE92570E04832178FDA7661D9E2583171FA4D31E37EB14 (528 bytes)
    EAD678EF037F7173B7AAD1890000A4EA3305165B3DAE6343D2CBA9FDF6A2AF75 (369 bytes)
    47BD977B957619C2B4D084BB897312032D611DD22882B15A1FBDD610C466FDB4 (369 bytes)
    026F1E862BAAAE7585558D5179985FDABDCD5CEDFE8036764BA745B0D0B186F4 (369 bytes)
    85FA51B979BE4147518A753ACF6FABA31A6C1411225069204AA9B903894B1F8A (369 bytes)
    BAE86BC946EE1FB35110C37FE43D3A7D9619C87290124DF53CDD4D59BF1FBC9C (369 bytes)
    18487F70A5AE6C87858988D244CCE3F64711360CFDD366DC198EF74F151CDCB8 (369 bytes)
    8F6181B46D13D7EBAD565F9B2B2608ECE2BA172AE3A16C385B41E390E58FE1E5 (369 bytes)
    40C2399D5D3EAEC641635CE43997B298FB7F95FA044B372785B777F9188130FA (528 bytes)
    1C8725A9498F95D5149152F98371058C166AE92089728AFA82BA83A755EEBB95 (369 bytes)
    2344A27A4D984A02809A3888637D3C0B1EFD34613DD9D7B143C2F31FFAA08004 (369 bytes)
    8A10F298F50A1C8A1056834DD157A4FC0079BEA49E8F94EE171E5B2329A014BC (369 bytes)
    FAAFB5E1D5FE68539C6DE03757DD04B032472248EE9EB19A4DCF33F4604BE145 (529 bytes)
    FF22E9D0B0503562F9A174D36E4865C46E9A743A54CE812FE53FDD2A9686A876 (528 bytes)
    FB22021FF6FC5F97629FCE7883E5BB488799D8A5B0ADA53810004DA3688034A8 (529 bytes)
  }#831B084AA1E87DBF15879B6E854437F0A21B473B32BD0C19BC934FAE6DEE27FE
  EvidenceData{

  }#E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
  Commit{
    Height:     1073104
    Round:      0
    BlockID:    28647082CB54E6F93A6DC83FF4D414FEEF759CFB9E6760ACEC8DEC78BB2E2E53:1:857D56FF9983
    Signatures:
      CommitSig{B11FC0442A43 by 4BC2DBE39A96 on 2 @ 2021-10-08T13:04:44.211856929Z}
      CommitSig{6334FD7BB9C9 by 8A3B04DB5007 on 2 @ 2021-10-08T13:04:44.186375962Z}
      CommitSig{B0420EC9BCB6 by 8BD806107E29 on 2 @ 2021-10-08T13:04:44.197290102Z}
      CommitSig{DCBDD0023E25 by 930C23CE7536 on 2 @ 2021-10-08T13:04:44.186642446Z}
  }#B6DD5A8882DCB11E9000494903D28461E6E73E8931DFA0AB72009965D9D9D461
}#EDE0A46D4DC456EEA82AE5869995D3A5A51472BC07F1ACC886B36C4C14507393


goroutine 1 [running]:
github.com/tendermint/tendermint/consensus.assertAppHashEqualsOneFromBlock(0xc0116b1420, 0x20, 0x20, 0xc01a0a8780)
        /home/user/godata/pkg/mod/github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:515 +0x18c
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(0xc01a0b8d58, 0xb, 0x0, 0x0, 0x0, 0xc01e8b2798, 0x6, 0x1, 0x1061a6, 0xc01167ebc0, ...)
        /home/user/godata/pkg/mod/github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:468 +0x2ed
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc01a0b8d58, 0xb, 0x0, 0x0, 0x0, 0xc01e8b2798, 0x6, 0x1, 0x1061a6, 0xc01167ebc0, ...)
        /home/user/godata/pkg/mod/github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:393 +0x8f0
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc01a0b8d58, 0x1649858, 0xc01e30dad0, 0xc0000f81a0, 0xc01e87fb30)
        /home/user/godata/pkg/mod/github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x1646c28, 0xc01e8b4580, 0xb, 0x0, 0x0, 0x0, 0xc01e8b2798, 0x6, 0x1, 0x1061a6, ...)
        /home/user/godata/pkg/mod/github.com/tendermint/tendermint@v0.34.10/node/node.go:308 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc000b50140, 0x16340a8, 0xc01e27f720, 0xc01e5d70f0, 0x161ab20, 0xc01e64d188, 0xc01e5d72a0, 0x14f5840, 0xc01e5d72b0, 0x163a7a8, ...)
        /home/user/godata/pkg/mod/github.com/tendermint/tendermint@v0.34.10/node/node.go:715 +0x2025
main.startTmNode(0xc000b50140, 0xc01e5d70f0, 0x1648aa0, 0xc0000a9600, 0x163a7a8, 0xc01daf7d00, 0x1, 0x37, 0x0)
        /home/user/smart_bch/smartbch/cmd/smartbchd/start.go:176 +0x296
main.startInProcess(0xc00000f4e8, 0x14f7178, 0x27, 0x0, 0x0)
        /home/user/smart_bch/smartbch/cmd/smartbchd/start.go:114 +0x34b
main.StartCmd.func1(0xc0003c2c80, 0xc0003d86c0, 0x0, 0x3, 0x0, 0x0)
        /home/user/smart_bch/smartbch/cmd/smartbchd/start.go:59 +0x85
github.com/spf13/cobra.(*Command).execute(0xc0003c2c80, 0xc0003d8660, 0x3, 0x3, 0xc0003c2c80, 0xc0003d8660)
        /home/user/godata/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003c2500, 0x1225ee0, 0xc00016fec0, 0xc0000c9f30)
        /home/user/godata/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...) 
        /home/user/godata/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0003c2500, 0x14f75e0, 0x2, 0xc0003ba6d8)
        /home/user/godata/pkg/mod/github.com/tendermint/tendermint@v0.34.10/libs/cli/setup.go:89 +0x4a
main.main()
        /home/user/smart_bch/smartbch/cmd/smartbchd/main.go:20 +0x70
$
```

**Comment by zxh0** [comment]
This is caused by the 'VRS' bug fix (issue 25), we will revert it and need some time to fix this, sorry.
