### ISSUE TITLE
v0.4.0 Fail to Sync mainnet

### ISSUE THREAD

**Issue by llwslc** [smartbch/smartbch#39]
mainnet: https://github.com/gcash/bchd

My mainnet rpc should be fine, because in version 0.3.5 it can get the mainnet block height.

What's wrong with my environment?

```
curl --user 'user:pass' --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblockcount", "params": [] }' -H 'content-type: text/plain;'  https://localhost:8334
{"jsonrpc":"1.0","result":724572,"error":null,"id":"curltest"}
```

v0.4.0
```
ScanEntriesLite 0.95 140112/147456
ScanEntriesLite 0.95 140184/147528
D[2022-01-27|03:59:43.805] New watcher: mainnet url(https://localhost:8334), epochNum(0), lastEpochEndHeight(698502), speedUp(false)
 module=app
get bch block hash
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/smartbch/smartbch/watcher.(*RpcClient).getBCHBlock(0x1466b40, {0xc00004cf00, 0x11bc8c3})
	/smart/smartbch/smartbch/watcher/rpcclient.go:155 +0x3f4
github.com/smartbch/smartbch/watcher.(*RpcClient).GetBlockByHeight(0xc0119d6de0, 0x0, 0x0)
	/smart/smartbch/smartbch/watcher/rpcclient.go:86 +0x23d
github.com/smartbch/smartbch/watcher.(*Watcher).CheckSanity(0xc00016a270, 0xf0)
	/smart/smartbch/smartbch/watcher/watcher.go:318 +0x54
github.com/smartbch/smartbch/app.NewApp(0xc000574d00, 0xc000f94780, 0xaa886, 0x1e, {0x1487e30, 0xc000f81f60}, 0x40)
	/smart/smartbch/smartbch/app/app.go:198 +0xf65
main.newApp({0x1487e30, 0xc000f81f60}, 0x11abcf0, 0xc000f946c0)
	/smart/smartbch/smartbch/cmd/smartbchd/main.go:53 +0xad
main.startInProcess(0xc000218ab0, 0x133f538)
	/smart/smartbch/smartbch/cmd/smartbchd/start.go:114 +0xd4
main.StartCmd.func1(0xc000294000, {0xc0001294c0, 0x0, 0x4})
	/smart/smartbch/smartbch/cmd/smartbchd/start.go:64 +0x57
github.com/spf13/cobra.(*Command).execute(0xc000294000, {0xc000129480, 0x4, 0x4})
	/root/godata/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000159680)
	/root/godata/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/root/godata/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/tendermint/tendermint/libs/cli.Executor.Execute({0xc000159680, 0x133f7e8})
	/root/godata/pkg/mod/github.com/tendermint/tendermint@v0.34.10/libs/cli/setup.go:89 +0x4a
main.main()
	/smart/smartbch/smartbch/cmd/smartbchd/main.go:20 +0x3d
```

v0.3.5
```
ScanEntriesLite 0.75 110664/147528
ScanEntriesLite 0.80 118080/147528
ScanEntriesLite 0.85 125424/147528
ScanEntriesLite 0.90 132768/147528
ScanEntriesLite 0.95 140184/147528
D[2022-01-27|03:56:39.442] New watcher: mainnet url(https://localhost:8334), epochNum(0), lastEpochEndHeight(698502), speedUp(false)
 module=app
pre fetch bch blocks: #698504 ~ #698513, latest: #724571
D[2022-01-27|03:56:39.504] getBCHBlock failed                           module=watcher invalidcharacter'T'aftertop-levelvalue=(MISSING)
D[2022-01-27|03:56:39.516] getBCHBlock failed                           module=watcher getTxerror,code:-8,msg:Failedtoparserequest:wrongnumberofparams(expectedbetween1and2,received3)=(MISSING)
D[2022-01-27|03:56:39.518] getBCHBlock failed                           module=watcher getTxerror,code:-8,msg:Failedtoparserequest:wrongnumberofparams(expectedbetween1and2,received3)=(MISSING)
D[2022-01-27|03:56:39.548] getBCHBlock failed                           module=watcher getTxerror,code:-8,msg:Failedtoparserequest:wrongnumberofparams(expectedbetween1and2,received3)=(MISSING)
D[2022-01-27|03:56:39.557] getBCHBlock failed                           module=watcher getTxerror,code:-8,msg:Failedtoparserequest:wrongnumberofparams(expectedbetween1and2,received3)=(MISSING)
D[2022-01-27|03:56:39.587] getBCHBlock failed                           module=watcher getTxerror,code:-8,msg:Failedtoparserequest:wrongnumberofparams(expectedbetween1and2,received3)=(MISSING)
D[2022-01-27|03:56:39.588] getBCHBlock failed                           module=watcher getTxerror,code:-8,msg:Failedtoparserequest:wrongnumberofparams(expectedbetween1and2,received3)=(MISSING)
D[2022-01-27|03:56:39.601] getBCHBlock failed                           module=watcher getTxerror,code:-8,msg:Failedtoparserequest:wrongnumberofparams(expectedbetween1and2,received3)=(MISSING)
D[2022-01-27|03:56:39.624] getBCHBlock failed                           module=watcher getTxerror,code:-8,msg:Failedtoparserequest:wrongnumberofparams(expectedbetween1and2,received3)=(MISSING)
D[2022-01-27|03:56:39.643] getBCHBlock failed                           module=watcher getTxerror,code:-8,msg:Failedtoparserequest:wrongnumberofparams(expectedbetween1and2,received3)=(MISSING)
D[2022-01-27|03:56:39.665] getBCHBlock failed                           module=watcher getTxerror,code:-8,msg:Failedtoparserequest:wrongnumberofparams(expectedbetween1and2,received3)=(MISSING)
D[2022-01-27|03:56:41.639] getBCHBlock failed                           module=watcher getTxerror,code:-8,msg:Failedtoparserequest:wrongnumberofparams(expectedbetween1and2,received3)=(MISSING)
```

**Comment by zxh0** [comment]
hi, looks like this problem is not related to smartbch v0.4.0 
It is caused by difference of `getrawtransaction` RPC implementation between [BCHD](https://github.com/gcash/bchd/blob/87534217bfc8d2c73461f025b5330f145aed9e86/docs/json_rpc_api.md#getrawtransaction
) and [BCHN](https://docs.bitcoincashnode.org/doc/json-rpc/getrawtransaction/
).
v0.4.0 let this problem exposed at startup time (from v0.3.5 log, the problem is there).  
Currently, smartbch only works well with BCHN node, so we suggest that you switch to BCHN node.
We will consider to improve this later. Thank you.

**Comment by llwslc** [comment]
Please state this in the docs.

```
# BCH mainnet rpc url (Only supprot BCHN)
mainnet-rpc-url = "http://ip-address:8332"

# BCH mainnet rpc username
mainnet-rpc-username = "<my user name>"

# BCH mainnet rpc password
mainnet-rpc-password = "<my password>"
```

**Comment by zxh0** [comment]
OK, we will improve the docs.
