### ISSUE TITLE
docker commands fail

### ISSUE THREAD

**Issue by allenday** [smartbch/smartbch#6]
In the docs for how to set up a local test environment with docker:

https://github.com/smartbch/smartbch/blame/main/README.md#L16

The command:
docker run c07742d4134c init mynode --chain-id 0x1 --init-balance=10000000000000000000 --test-keys=key1,key2,etc

Doesn't work. It gives an error:
`ERROR: genesis.json file already exists: /root/.smartbchd/config/genesis.json`

**Comment by zxh0** [comment]
I have removed the mistakenly added `smartbchd init` cmd in the Dockerfile, it should fix this issue

**Comment by allenday** [comment]
I tried removing it as well, but then got stuck as the readme script is not complete. Can you please update it also?

Thx @zxh0

**Comment by zxh0** [comment]
Sorry for that @allenday 
We have released a new version v0.1.6 just now and README is updated.
Please try again and let me know if you still have problems. Thank you.

**Comment by allenday** [comment]
pulled today. still failing.

```
docker-compose up

Docker Compose is now in the Docker CLI, try `docker compose up`

Creating smartbch_smartbch_1 ... done
Attaching to smartbch_smartbch_1
smartbch_1  | I[2021-06-01|10:36:03.632] starting SmartBCH Chain with Tendermint      module=main 
smartbch_1  | OldSize entryFile 0 twigMtFile 0
smartbch_1  | NewSize entryFile 0 twigMtFile 0
smartbch_1  | panic: EOF
smartbch_1  | 
smartbch_1  | goroutine 35 [running]:
smartbch_1  | github.com/smartbch/moeingads/datatree.(*TwigMtFile).GetFirstEntryPos(0xc000200150, 0x0, 0x0)
smartbch_1  | 	/go/pkg/mod/github.com/smartbch/moeingads@v0.1.2-0.20210529030049-8a9751f4d351/datatree/twigmtfile.go:50 +0x178
smartbch_1  | github.com/smartbch/moeingads/datatree.(*Tree).ScanEntries(0xc000d40000, 0x0, 0xc000db21e0)
smartbch_1  | 	/go/pkg/mod/github.com/smartbch/moeingads@v0.1.2-0.20210529030049-8a9751f4d351/datatree/load_dump.go:340 +0x45
smartbch_1  | created by github.com/smartbch/moeingads/datatree.(*Tree).RecoverActiveTwigs
smartbch_1  | 	/go/pkg/mod/github.com/smartbch/moeingads@v0.1.2-0.20210529030049-8a9751f4d351/datatree/load_dump.go:371 +0x89
smartbch_1  | I[2021-06-01|10:36:12.280] starting SmartBCH Chain with Tendermint      module=main 
smartbch_1  | OldSize entryFile 0 twigMtFile 0
smartbch_1  | NewSize entryFile 0 twigMtFile 0
smartbch_1  | panic: EOF
smartbch_1  | 
smartbch_1  | goroutine 67 [running]:
smartbch_1  | github.com/smartbch/moeingads/datatree.(*TwigMtFile).GetFirstEntryPos(0xc000124050, 0x0, 0xe64479)
smartbch_1  | 	/go/pkg/mod/github.com/smartbch/moeingads@v0.1.2-0.20210529030049-8a9751f4d351/datatree/twigmtfile.go:50 +0x178
smartbch_1  | github.com/smartbch/moeingads/datatree.(*Tree).ScanEntries(0xc000d2c000, 0x0, 0xc0001807e0)
smartbch_1  | 	/go/pkg/mod/github.com/smartbch/moeingads@v0.1.2-0.20210529030049-8a9751f4d351/datatree/load_dump.go:340 +0x45
smartbch_1  | created by github.com/smartbch/moeingads/datatree.(*Tree).RecoverActiveTwigs
smartbch_1  | 	/go/pkg/mod/github.com/smartbch/moeingads@v0.1.2-0.20210529030049-8a9751f4d351/datatree/load_dump.go:371 +0x89
smartbch_smartbch_1 exited with code 2
smartbch_1  | I[2021-06-01|10:36:20.727] starting SmartBCH Chain with Tendermint      module=main 
smartbch_1  | OldSize entryFile 0 twigMtFile 0
smartbch_1  | NewSize entryFile 0 twigMtFile 0
smartbch_1  | panic: EOF
smartbch_1  | 
smartbch_1  | goroutine 22 [running]:
smartbch_1  | github.com/smartbch/moeingads/datatree.(*TwigMtFile).GetFirstEntryPos(0xc000180d18, 0x0, 0x0)
smartbch_1  | 	/go/pkg/mod/github.com/smartbch/moeingads@v0.1.2-0.20210529030049-8a9751f4d351/datatree/twigmtfile.go:50 +0x178
smartbch_1  | github.com/smartbch/moeingads/datatree.(*Tree).ScanEntries(0xc000d0a000, 0x0, 0xc000140ea0)
smartbch_1  | 	/go/pkg/mod/github.com/smartbch/moeingads@v0.1.2-0.20210529030049-8a9751f4d351/datatree/load_dump.go:340 +0x45
smartbch_1  | created by github.com/smartbch/moeingads/datatree.(*Tree).RecoverActiveTwigs
smartbch_1  | 	/go/pkg/mod/github.com/smartbch/moeingads@v0.1.2-0.20210529030049-8a9751f4d351/datatree/load_dump.go:371 +0x89
smartbch_smartbch_1 exited with code 2
smartbch_1  | I[2021-06-01|10:36:31.151] starting SmartBCH Chain with Tendermint      module=main 
smartbch_1  | OldSize entryFile 0 twigMtFile 0
smartbch_1  | NewSize entryFile 0 twigMtFile 0
smartbch_1  | panic: EOF
smartbch_1  | 
smartbch_1  | goroutine 84 [running]:
smartbch_1  | github.com/smartbch/moeingads/datatree.(*TwigMtFile).GetFirstEntryPos(0xc000124d30, 0x0, 0x0)
smartbch_1  | 	/go/pkg/mod/github.com/smartbch/moeingads@v0.1.2-0.20210529030049-8a9751f4d351/datatree/twigmtfile.go:50 +0x178
smartbch_1  | github.com/smartbch/moeingads/datatree.(*Tree).ScanEntries(0xc000380000, 0x0, 0xc000d8a180)
smartbch_1  | 	/go/pkg/mod/github.com/smartbch/moeingads@v0.1.2-0.20210529030049-8a9751f4d351/datatree/load_dump.go:340 +0x45
smartbch_1  | created by github.com/smartbch/moeingads/datatree.(*Tree).RecoverActiveTwigs
smartbch_1  | 	/go/pkg/mod/github.com/smartbch/moeingads@v0.1.2-0.20210529030049-8a9751f4d351/datatree/load_dump.go:371 +0x89
smartbch_smartbch_1 exited with code 2
```

**Comment by zxh0** [comment]
can not reproduce this problem on my macbook : (
could you remove the volume `smartbch_smartbch_data` and clean restart the container to see if the problem still happen ?

**Comment by wangkui0508** [comment]
The error looks like there is an old /root/.smartbchd directory and smartbchd is reading it when starting another chain.
I cannot reproduce it either.

**Comment by allenday** [comment]
I'll prune the entire docker on this host and try again

**Comment by zquestz** [comment]
This should be closed. The latest docker image is working as expected. =)
